@startuml

ReentrantLock -> ReentrantLock: tryLock
activate ReentrantLock
    ReentrantLock->Sync:nonfairTryAcquire
    activate Sync
    ReentrantLock<--Sync:
    deactivate Sync
ReentrantLock --> ReentrantLock:
deactivate ReentrantLock

@enduml